apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
  name: eureka-server
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
    nodePort: 30761
  selector:
    app: eureka-server
  type: NodePort
